version: '3.8'

services:
  weapon-service:
    build:
      context: ./Weapon
      dockerfile: Dockerfile
    restart: always
    environment:
      - AUI_WEAPONTYPE_URL=http://weapontype-service:8082/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://weapon-db:5432/weapon-database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    container_name: weapon-service
    ports:
      - "8081:8081"
    depends_on:
      - weapon-db
    networks:
      - mynetwork

  weapontype-service:
    build:
      context: ./WeaponType
      dockerfile: Dockerfile
    restart: always
    environment:
      - AUI_WEAPON_URL=http://weapon-service:8081/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://weapontype-db:5432/weapontype-database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    container_name: weapontype-service
    ports:
      - "8082:8082"
    depends_on:
      - weapontype-db
    networks:
      - mynetwork

  gateway-service:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    restart: always
    environment:
      - AUI_GATEWAY_HOST=http://gateway-service:8080
      - AUI_WEAPON_URL=http://weapon-service:8081
      - AUI_WEAPONTYPE_URL=http://weapontype-service:8082
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - weapon-service
      - weapontype-service
    networks:
      - mynetwork

  simple-rpg-ng-frontend:
    build:
      context: ./simple-rpg-ng
      dockerfile: Dockerfile
    restart: always
    environment:
      - API_URL=http://gateway-service:8080/api
    container_name: simple-rpg-ng-frontend
    ports:
      - "4200:80"
    depends_on:
      - gateway-service
    networks:
      - mynetwork

  weapon-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weapon-database
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - weapon-db-data:/var/lib/postgresql/data
    container_name: weapon-db
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  weapontype-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weapontype-database
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - weapontype-db-data:/var/lib/postgresql/data
    container_name: weapontype-db
    ports:
      - "5434:5432" 
    networks:
      - mynetwork

volumes:
  weapon-db-data:
  weapontype-db-data:

networks:
  mynetwork:
    driver: bridge
