# Pobranie wszystkich broni
GET http://localhost:8081/api/weapons
Content-Type: application/json

###

# Pobranie wszystkich typów broni
GET http://localhost:8080/api/weapontypes
Content-Type: application/json

###

# Pobranie jednej broni na podstawie ID - nie istnieje
GET http://localhost:8080/api/weapons/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6
Content-Type: application/json

###

# Pobranie jednej broni na podstawie ID - istnieje
GET http://localhost:8080/api/weapons/c4804e0f-769e-4ab9-9ebe-0578fb4f00a7
Content-Type: application/json

###

# Pobranie jednego typu broni na podstawie ID
GET http://localhost:8080/api/weapontypes/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6
Content-Type: application/json

###

# Pobranie wszystkich broni z danej kategori
GET http://localhost:8080/api/weapons/weapontypes/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6
Content-Type: application/json

###

# Pobranie wszystkich broni z danej kategori - nie istnieje
GET http://localhost:8080/api/weapons/weapontypes/c4804x0f-769e-4ab9-9ebe-0578fb4f00a6
Content-Type: application/json

###

# Pobranie jednego typu broni na podstawie ID - nie istnieje
GET http://localhost:8080/api/weapontypes/c4804e0f-769e-4ab9-9ebe-0578fb4f00a0
Content-Type: application/json

###

# Utworzenie nowej broni
POST http://localhost:8080/api/weapons
Content-Type: application/json

{
  "name": "New Weapon",
  "damage": 50,
  "weaponTypeId": "c4804e0f-769e-4ab9-9ebe-0578fb4f00a6"
}

###

# Utworzenie nowego typu broni
POST http://localhost:8080/api/weapontypes
Content-Type: application/json

{
  "category": "New Weapon Type"
}

###

# Pobranie jednego typu broni na podstawie ID - puste
GET http://localhost:8080/api/weapontypes/ff4183ff-9bfb-4687-9b0b-b1ad03996472
Content-Type: application/json

###

# Aktualizacja nieistniejacej broni
PUT http://localhost:8080/api/weapons/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6
Content-Type: application/json

{
  "name": "Updated Weapon Name",
  "damage": 100,
  "weaponTypeId": "c4804e0f-769e-4ab9-9ebe-0578fb4f00a7"
}

###

# Aktualizacja istniejacej broni
PUT http://localhost:8080/api/weapons/c4804e0f-769e-4ab9-9ebe-0578fb4f00a7
Content-Type: application/json

{
  "name": "Updated Weapon Name",
  "damage": 100,
  "weaponTypeId": "c4804e0f-769e-4ab9-9ebe-0578fb4f00a6"
}

###

# Usunięcie broni na podstawie ID
DELETE http://localhost:8080/api/weapons/c4804e0f-769e-4ab9-9ebe-0578fb4f00a7
Content-Type: application/json

###

# Usunięcie kategori broni na podstawie ID
DELETE http://localhost:8080/api/weapontypes/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6
Content-Type: application/json
